name: Run Queries

on:
  # manual run
  workflow_dispatch:

jobs:
  create-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '309.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name:
        run: |
          bq --location=US mk \
          --dataset \
          --default_table_expiration 604800 \
          --description "@uniswap/retroactive-query output for commit ${{ github.sha }}" \
          ${{ secrets.GCP_PROJECT_ID }}:retroactive_${{ github.sha }}

  run-queries:
    needs: create-dataset
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        schema:
          - file: "./src/v1.sql"
          - file: "./src/v2_dai.sql"
          - file: "./src/v2_sai.sql"
          - file: "./src/v2_usdc.sql"
          - file: "./src/v2_usdc_pod.sql"
          - file: "./src/v2_dai_pod.sql"
          - file: "./src/v3_dai.sql"
          - file: "./src/v3_uni.sql"
          - file: "./src/v3_usdc.sql"
          - file: "./src/all_versions.sql"


    steps:
      - uses: actions/checkout@v2

      - name: Setup gcloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '309.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name:
        run: |
          cat ${{ matrix.schema.file }} | \
          bq --location=US --dataset_id=${{ secrets.GCP_PROJECT_ID }}:retroactive_${{ github.sha }} query \
          --use_legacy_sql=false \
          --parameter='v3_cutoff_block_number:INT64:11656283' \
          --parameter='v2_cutoff_block_number:INT64:11104391' \
          --parameter='v1_pool_period:INT64:36000' \
          --parameter='user_reward:FLOAT64:400' \
          --parameter='total_reward:FLOAT64:150000000' 

